
CREATE TABLE USER (
    ID INT NOT NULL auto_increment,
    FULL_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    PHONE_NO VARCHAR(10) NOT NULL,
    CREATED_TIME DATETIME default CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIES (
    ID INT NOT NULL auto_increment,
    TITLE VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BLOGS (
    ID INT NOT NULL auto_increment,
    TITLE VARCHAR(20) NOT NULL,
    CONTENTS VARCHAR(30) NOT NULL,
    CREATED_TIME DATETIME default CURRENT_TIMESTAMP NOT NULL,
    USER_ID INT,
    CATEGORY_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

CREATE INDEX USER_EMAIL_INDEX ON USER(EMAIL);
CREATE INDEX BLOGS_USER_INDEX ON BLOGS(USER_ID);
CREATE INDEX BLOGS_CATEGORY_INDEX ON BLOGS(CATEGORY_ID);